=== daangn/seed-design/docs/schema/component-meta.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Component Meta Schema for Seed Design System",
  "description": "컴포넌트 메타 정보들에 대한 스키마입니다.",
  "type": "object",
  "definitions": {
    "status": {
      "title": "진행 상태",
      "description": "진행 상태",
      "oneOf": [
        {
          "const": "todo",
          "title": "해야하는 작업",
          "description": "해야하는 작업"
        },
        {
          "const": "in-progress",
          "title": "진행중인 작업",
          "description": "진행중인 작업"
        },
        {
          "const": "done",
          "title": "완료된 작업",
          "description": "완료된 작업"
        }
      ],
      "default": "todo"
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "title": "컴포넌트 이름"
    },
    "description": {
      "type": "string",
      "title": "컴포넌트 설명"
    },
    "thumbnail": {
      "type": "string",
      "pattern": "^.*.png$",
      "title": "컴포넌트 썸네일 이미지 경로",
      "description": "png 파일만 가능합니다."
    },
    "primitive": {
      "type": "string",
      "pattern": "^.*.json$",
      "title": "컴포넌트 primitive json 메타 파일 경로",
      "description": "json 파일만 가능합니다."
    },
    "platform": {
      "type": "object",
      "title": "컴포넌트의 플랫폼별 정보",
      "properties": {
        "ios": {
          "type": "object",
          "title": "iOS 플랫폼 정보",
          "properties": {
            "status": {
              "$ref": "#/definitions/status"
            },
            "alias": {
              "type": "string",
              "title": "컴포넌트 iOS alias",
              "description": "컴포넌트의 iOS alias를 입력해주세요. (optional)"
            },
            "path": {
              "type": "string",
              "oneOf": [
                {
                  "pattern": "^seedcatalog://.*$"
                },
                {
                  "pattern": "^$"
                }
              ],
              "title": "컴포넌트 iOS 경로",
              "description": "컴포넌트의 iOS Deep link를 입력해주세요."
            }
          },
          "required": ["status", "alias", "path"],
          "additionalProperties": false
        },
        "android": {
          "type": "object",
          "title": "Android 플랫폼 정보",
          "properties": {
            "status": {
              "$ref": "#/definitions/status"
            },
            "path": {
              "type": "string",
              "title": "컴포넌트 Android 경로",
              "description": "컴포넌트의 Android Deep link를 입력해주세요."
            }
          },
          "required": ["status", "path"],
          "additionalProperties": false
        },
        "react": {
          "type": "object",
          "title": "React 플랫폼 정보",
          "properties": {
            "status": {
              "$ref": "#/definitions/status"
            },
            "path": {
              "type": "string",
              "title": "컴포넌트 React Sprout 경로",
              "description": "컴포넌트의 React Sprout Storybook link를 입력해주세요.",
              "oneOf": [
                {
                  "pattern": "^https://sprout-storybook.vercel.app/.*$"
                },
                {
                  "pattern": "^$"
                }
              ]
            }
          },
          "required": ["status", "path"],
          "additionalProperties": false
        },
        "figma": {
          "type": "object",
          "title": "Figma 플랫폼 정보",
          "properties": {
            "status": {
              "$ref": "#/definitions/status"
            },
            "path": {
              "type": "string",
              "oneOf": [
                {
                  "pattern": "^https://www.figma.com/file/.*$"
                },
                {
                  "pattern": "^$"
                }
              ],
              "title": "컴포넌트 Figma 경로",
              "description": "컴포넌트의 Figma link를 입력해주세요."
            }
          },
          "required": ["status", "path"],
          "additionalProperties": false
        },
        "docs": {
          "type": "object",
          "title": "Seed Docs 플랫폼 정보",
          "properties": {
            "overview": {
              "type": "object",
              "title": "컴포넌트 Overview 정보",
              "description": "컴포넌트의 전반적인 내용이 들어가있습니다.",
              "properties": {
                "status": {
                  "$ref": "#/definitions/status"
                },
                "storybook": {
                  "type": "object",
                  "title": "컴포넌트 Storybook 정보",
                  "description": "컴포넌트의 Storybook에 대한 정보가 들어가있습니다.",
                  "properties": {
                    "path": {
                      "type": "string",
                      "title": "컴포넌트 Storybook 경로",
                      "description": "Iframe에 띄울 Storybook 경로를 입력해주세요."
                    },
                    "height": {
                      "type": "string",
                      "title": "Iframe 높이",
                      "description": "Iframe의 높이를 입력해주세요."
                    }
                  },
                  "required": ["path", "height"]
                },
                "mdx": {
                  "type": "string",
                  "pattern": "overview.mdx$",
                  "title": "컴포넌트 Overview MDX 문서 경로",
                  "description": "컴포넌트의 Overview MDX 문서 경로를 입력해주세요."
                }
              },
              "required": ["status", "mdx"],
              "additionalProperties": false
            },
            "usage": {
              "type": "object",
              "title": "컴포넌트 Usage 정보",
              "description": "컴포넌트의 사용법에 대한 정보가 들어가있습니다.",
              "properties": {
                "status": {
                  "$ref": "#/definitions/status"
                },
                "mdx": {
                  "type": "string",
                  "pattern": "usage.mdx$",
                  "title": "컴포넌트 Usage MDX 문서 경로",
                  "description": "컴포넌트의 Usage MDX 문서 경로를 입력해주세요."
                }
              },
              "required": ["status", "mdx"],
              "additionalProperties": false
            },
            "style": {
              "type": "object",
              "title": "컴포넌트 Style 정보",
              "description": "컴포넌트의 스타일 가이드에 대한 정보가 들어가있습니다.",
              "properties": {
                "status": {
                  "$ref": "#/definitions/status"
                },
                "mdx": {
                  "type": "string",
                  "pattern": "style.mdx$",
                  "title": "컴포넌트 Style MDX 문서 경로",
                  "description": "컴포넌트의 Style MDX 문서 경로를 입력해주세요."
                }
              },
              "required": ["status", "mdx"],
              "additionalProperties": false
            }
          },
          "required": ["overview", "usage", "style"],
          "additionalProperties": false
        }
      },
      "required": ["ios", "android", "react", "figma", "docs"],
      "additionalProperties": false
    }
  },
  "required": ["name", "description", "thumbnail", "platform"]
}

=== daangn/seed-design/docs/content/component/alert-dialog/component-meta.json
{
  "name": "Alert Dialog",
  "description": "",
  "thumbnail": "../../comingSoon.png",
  "platform": {
    "ios": {
      "status": "todo",
      "alias": "",
      "path": ""
    },
    "android": {
      "status": "todo",
      "path": ""
    },
    "react": {
      "status": "in-progress",
      "path": ""
    },
    "figma": {
      "status": "todo",
      "path": ""
    },
    "docs": {
      "overview": {
        "status": "todo",
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "in-progress",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "done",
        "mdx": "./style.mdx"
      }
    }
  }
}

=== daangn/seed-design/docs/content/component/bottom-sheet/component-meta.json
{
  "name": "Bottom Sheet",
  "description": "화면 하단에 고정된 보충 콘텐츠가 포함된 표면 요소입니다.",
  "thumbnail": "../../comingSoon.png",
  "platform": {
    "ios": {
      "status": "todo",
      "alias": "",
      "path": ""
    },
    "android": {
      "status": "todo",
      "path": ""
    },
    "react": {
      "status": "todo",
      "path": ""
    },
    "figma": {
      "status": "todo",
      "path": ""
    },
    "docs": {
      "overview": {
        "status": "todo",
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "in-progress",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "in-progress",
        "mdx": "./style.mdx"
      }
    }
  }
}

=== daangn/seed-design/docs/content/component/slider/component-meta.json
{
  "$schema": "../../../schema/component-meta.json",
  "name": "Slider",
  "description": "범위 내 값을 조정할 수 있는 요소입니다.",
  "thumbnail": "./thumbnail.png",
  "platform": {
    "ios": {
      "status": "todo",
      "alias": "",
      "path": ""
    },
    "android": {
      "status": "todo",
      "path": ""
    },
    "react": {
      "status": "done",
      "path": "https://sprout-storybook.vercel.app/?path=/docs/components-slider-slider--docs"
    },
    "figma": {
      "status": "todo",
      "path": ""
    },
    "docs": {
      "overview": {
        "status": "in-progress",
        "storybook": {
          "path": "https://sprout-storybook.vercel.app/iframe.html?args=&id=components-slider-slider--basic&viewMode=story",
          "height": "80px"
        },
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "in-progress",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "done",
        "mdx": "./style.mdx"
      }
    }
  }
}

=== daangn/seed-design/docs/content/component/action-sheet/component-meta.json
{
  "$schema": "../../../schema/component-meta.json",
  "name": "Action Sheet",
  "description": "OS 시스템 액션시트를 대체하는 커스텀 액션시트입니다.",
  "thumbnail": "./thumbnail.png",
  "primitive": "../../primitive/menu/primitive-meta.json",
  "platform": {
    "ios": {
      "status": "done",
      "alias": "",
      "path": "seedcatalog://components/action-sheet"
    },
    "android": {
      "status": "done",
      "path": ""
    },
    "react": {
      "status": "todo",
      "path": ""
    },
    "figma": {
      "status": "done",
      "path": "https://www.figma.com/file/ty7UxJ61CVPeVU2Gf1LJGQ/App-Components?type=design&node-id=35319-33895&t=WVhT3hdC8rK21W3o-4"
    },
    "docs": {
      "overview": {
        "status": "in-progress",
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "in-progress",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "done",
        "mdx": "./style.mdx"
      }
    }
  }
}

=== daangn/seed-design/docs/content/component/checkbox/component-meta.json
{
  "$schema": "../../../schema/component-meta.json",
  "name": "Checkbox",
  "description": "최소 1가지 이상의 옵션을 선택 또는 해제할 수 있는 컨트롤입니다.",
  "thumbnail": "./thumbnail.png",
  "primitive": "../../primitive/checkbox/primitive-meta.json",
  "platform": {
    "ios": {
      "status": "done",
      "alias": "KarrotCheckbox",
      "path": "seedcatalog://components/checkbox"
    },
    "android": {
      "status": "todo",
      "path": ""
    },
    "react": {
      "status": "done",
      "path": "https://sprout-storybook.vercel.app/?path=/docs/components-checkbox--docs"
    },
    "figma": {
      "status": "done",
      "path": "https://www.figma.com/file/ty7UxJ61CVPeVU2Gf1LJGQ/App-Components?type=design&node-id=51258-39461&t=WVhT3hdC8rK21W3o-4"
    },
    "docs": {
      "overview": {
        "status": "done",
        "storybook": {
          "path": "https://sprout-storybook.vercel.app/iframe.html?args=&id=components-checkbox--basic&viewMode=story",
          "height": "75px"
        },
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "done",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "done",
        "mdx": "./style.mdx"
      }
    }
  }
}

=== daangn/seed-design/docs/content/component/switch/component-meta.json
{
  "$schema": "../../../schema/component-meta.json",
  "name": "Switch",
  "description": "사용자가 개별 옵션을 켜거나 끌 수 있는 컨트롤입니다. 일반적으로 설정을 제어하기 위해 사용됩니다.",
  "thumbnail": "./thumbnail.png",
  "platform": {
    "ios": {
      "status": "done",
      "alias": "",
      "path": "seedcatalog://components/switch"
    },
    "android": {
      "status": "todo",
      "path": ""
    },
    "react": {
      "status": "done",
      "path": "https://sprout-storybook.vercel.app/?path=/docs/components-switch--docs"
    },
    "figma": {
      "status": "done",
      "path": "https://www.figma.com/file/ty7UxJ61CVPeVU2Gf1LJGQ/App-Components?type=design&node-id=51313-38966&t=WVhT3hdC8rK21W3o-4"
    },
    "docs": {
      "overview": {
        "status": "in-progress",
        "storybook": {
          "path": "https://sprout-storybook.vercel.app/iframe.html?args=&id=components-switch--basic&viewMode=story",
          "height": "80px"
        },
        "mdx": "./overview.mdx"
      },
      "usage": {
        "status": "in-progress",
        "mdx": "./usage.mdx"
      },
      "style": {
        "status": "done",
        "mdx": "./style.mdx"
      }
    }
  }
}
